### PR TITLE
Add helper function to memoize selector return values

### PR DESCRIPTION
**Pull request by emilsjolander**

### CODE REVIEW

**Comment by dentrado** [comment]
This solution might work in some situations, but I'm afraid it'll often be more expensive than without it. 
It assumes the selector is cheap to run and that the result is fast to deep compare, but I think that's often not the case. I think especially the deep compare of the list of latest calls can be slow (but would be interesting to measure)

**Comment by dentrado** [comment]
But I see now we use deepEqual already to decide if subscribers should be called, I guess it's most often fast, the worst case scenario might not happen in practice. I think it would be pretty easy to avoid rerunning the selector every time though

**Comment by dentrado** [comment]
I'll push a change that avoids calling the selector if its arguments haven't changed, more similar to how a regular function memoization works. Feel free to revert it if you think it's a bad idea.

**Comment by dentrado** [comment]
One example of an selector that's expensive to rerun would be the error search (that we don't currently have as a selector I think because it's expensive)

**Comment by emilsjolander** [comment]
@dentrado the problem with "standard" function memoization is that the arguments will in 99% of cases have changed as the arguments is the store itself.

**Comment by dentrado** [comment]
🤦 I forgot about that. That was why I thought it would be hard to do automatically in the first place. But it would be possible to do a two step selection. similar to how https://github.com/reduxjs/reselect works. 
```
export const components = memoSelector(
    ({ store: Store }) => store.remote.components,
    components => sortBy(values(components), 'name')
)
```

**Comment by dentrado** [comment]
Or it could take a variable number of arguments, so you can chain together how many selectors as you want, but you could also just call it with one function like your original version

**Comment by dentrado** [comment]
Maybe we should just use reselect directly. It's very small, well documented and has no dependencies on redux (or any library at all for that matter).

**Comment by emilsjolander** [comment]
That sounds reasonable!

**Pull request closed without merging**
